spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mysociety}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
logging:
  level:
    com.mysociety: DEBUG
    org.springframework.security: DEBUG

mysociety:
  security:
    hs256-secret: ${JWT_HS256_SECRET:8fK9xP2mQ7vL1zN4rT6yU0aS3dH5jW8c}
